"""Frozen GUI journey for an optional, cryptographically covered signature mark.

Only the ephemeral PFX generated by the v1.6.0 smoke is used for signing. The
normal Windows certificate listing stays read-only. The preview is rendered by
the PDF worker, and the saved appearance is inspected independently with pypdf.
"""
from io import BytesIO
import math
import tempfile
import uuid

from PySide6.QtCore import QTimer
from PySide6.QtWidgets import QApplication, QFileDialog

from .smoke import _digest
from .smoke_v160 import SmokeV160, test_certificate


class SmokeV161(SmokeV160):
    def __init__(self, window, source, report_path):
        super().__init__(window, source, report_path)
        self.signed_output = self.report_path.parent / ('smoke-v161-firmado-visible-' + uuid.uuid4().hex + '.pdf')
        self._require(self.signed_output.resolve() != self.source,
                      'La prueba no puede sobrescribir el original.')
        self.signature_preview = None
        self.signature_dialog = None
        self.signature_rect = [value * 72. / 25.4 for value in (20., 220., 180., 275.)]
        self.signature_render_checked = False
        self.before_signature_state = None

    def _begin_signature(self):
        try:
            self.secret_dir = tempfile.TemporaryDirectory(
                prefix='smoke-visible-sign-', dir=self.report_path.parent)
            path, password = test_certificate(self.secret_dir.name)
            self.stage = 'preparing_visible_signature'
            self.before_signature_state = dict(self.window.state)
            from .signing_ui import SignatureDialog
            timer = QTimer(self)
            self.signature_dialog_timer = timer

            def fill_dialog():
                dialog = QApplication.activeModalWidget()
                if not isinstance(dialog, SignatureDialog):
                    return
                timer.stop()
                try:
                    self.signature_dialog = dialog
                    index = dialog.source.findData('pfx')
                    self._require(index >= 0, 'Falta la vía PFX para la identidad sintética.')
                    self._require(not dialog.visible_signature.isChecked(),
                                  'La apariencia gráfica debe ser opcional.')
                    dialog.source.setCurrentIndex(index)
                    dialog.certificate.setText(str(path))
                    dialog.password.setText(password)
                    dialog.reason.setText('Prueba automática; identidad sintética no verificada')
                    dialog.location.setText('Prueba local')
                    dialog.visible_signature.setChecked(True)
                    dialog.signature_page.setCurrentIndex(0)
                    for control, value in ((dialog.signature_x, 20.), (dialog.signature_y, 220.),
                                           (dialog.signature_width, 160.), (dialog.signature_height, 55.)):
                        control.setValue(value)
                    self.stage = 'previewing_visible_signature'
                    self._step('visible_signature_enabled_with_page_and_dimensions')
                    dialog.preview_button.click()
                    self._require(self.window.busy and self.window._command == 'signature_preview',
                                  'La previsualización no solicitó el PDF real al proceso de trabajo.')
                except Exception as exc:
                    dialog.reject()
                    self.fail(str(exc))

            timer.timeout.connect(fill_dialog)
            self.saved_picker = QFileDialog.getSaveFileName
            QFileDialog.getSaveFileName = staticmethod(
                lambda *a, **k: (str(self.signed_output), 'Documento PDF (*.pdf)'))
            timer.start(20)
            self.window.sign_action.trigger()
            self._require(self.window.busy and self.window._command == 'list_signing_certificates',
                          'El botón Firmar no solicitó los certificados al proceso PDF.')
            self._step('signature_action_lists_windows_certificates')
        except Exception as exc:
            self.fail(str(exc))

    def _advance(self, command, result):
        if self.stage == 'previewing_visible_signature' and command == 'signature_preview':
            self._require(result.get('preview_only') is True and bool(result.get('png')),
                          'Falta la previsualización real sin firmar.')
            self._require(result.get('page') == 0, 'La firma se previsualizó en otra página.')
            self._require(all(abs(a-b) < .04 for a, b in zip(result['rect'], self.signature_rect)),
                          'La previsualización cambió la posición o dimensiones elegidas.')
            self._require('TEST ONLY' in result.get('certificate_subject', ''),
                          'La vista previa no corresponde al certificado sintético seleccionado.')
            for key in ('history_index', 'dirty', 'preview', 'page_count'):
                self._require(self.window.state[key] == self.before_signature_state[key],
                              'La previsualización de firma cambió el documento de trabajo.')
            self._require(not self.signed_output.exists(),
                          'La vista previa no debe escribir una copia firmada.')
            self.signature_preview = result
            (self.report_path.parent / 'smoke-v161-firma-preview.png').write_bytes(result['png'])
            self._step('signature_preview_from_pdf_without_signing',
                       page=result['page'], rect=result['rect'],
                       png_sha256=_digest(result['png']))
            self.stage = 'signing'
            # Let the worker callback finish updating the modal before accepting.
            QTimer.singleShot(0, self._accept_signature)
            return

        if self.stage == 'signing' and command == 'sign_pdf':
            self._assert_visible_widget(result['signature'])

        if self.stage == 'reopen_signed' and command == 'page' and not self.signature_render_checked:
            self._require(self.signature_preview is not None, 'No se registró la vista previa.')
            zoom = self.signature_preview['zoom']
            if abs(result['zoom'] - zoom) > .0001:
                self._require(self.window._submit('page', {'number': 0, 'zoom': zoom}),
                              'No se pudo comparar el render firmado con la vista previa.')
                return
            self._compare_appearance_render(result['png'])
            self.signature_render_checked = True

        super()._advance(command, result)

    def _accept_signature(self):
        if self.finished:
            return
        try:
            self._require(self.signature_dialog is not None and self.signature_dialog._preview_result,
                          'La interfaz no recibió el resultado de su previsualización.')
            self._require(self.signature_dialog.grab().save(
                str(self.report_path.parent / 'smoke-v161-dialog.png')),
                'No se pudo guardar la captura del diálogo y su vista previa.')
            self.signature_dialog.accept()
        except Exception as exc:
            if self.signature_dialog:
                self.signature_dialog.reject()
            self.fail(str(exc))

    def _assert_visible_widget(self, proof):
        from pypdf import PdfReader
        visible = proof.get('visible_signature')
        self._require(isinstance(visible, dict) and visible.get('page') == 0,
                      'La firma exportada no informa de su apariencia visible.')
        self._require(all(abs(a-b) < .04 for a, b in zip(visible['rect'], self.signature_rect)),
                      'La firma guardada cambió la posición o dimensiones elegidas.')
        self._require('TEST ONLY' in visible.get('certificate_subject', ''),
                      'La firma visible no identifica el certificado utilizado.')
        reader = PdfReader(BytesIO(self.signed_output.read_bytes()), strict=True)
        page = reader.pages[0]
        widgets = []
        for reference in page.get('/Annots', []):
            item = reference.get_object()
            field = item.get('/Parent', item).get_object()
            if item.get('/Subtype') == '/Widget' and field.get('/FT') == '/Sig':
                widgets.append(item)
        self._require(len(widgets) == 1, 'Se esperaba un único widget de firma en la página elegida.')
        widget = widgets[0]
        ap = widget['/AP']['/N'].get_object()
        # PDF rectangles can list either pair of opposite corners; pyHanko's
        # appearance helper writes top-left then bottom-right for its BBox.
        self._require(b'/SignatureArtwork Do' in ap.get_data()
                      and abs(ap['/BBox'][2] - ap['/BBox'][0]) > 0
                      and abs(ap['/BBox'][3] - ap['/BBox'][1]) > 0
                      and '/SignatureArtwork' in ap['/Resources']['/XObject'],
                      'El widget firmado no contiene una apariencia gráfica utilizable.')
        x0, y0, x1, y1 = map(float, widget['/Rect'])
        self._require(x1 > x0 and y1 > y0, 'La firma exportada sigue siendo invisible.')
        self._step('signed_widget_appearance_inspected_with_pypdf',
                   widget_rect=[x0, y0, x1, y1], page=0)

    def _compare_appearance_render(self, final_png):
        from PIL import Image, ImageChops
        before = Image.open(BytesIO(self.signature_preview['png'])).convert('RGB')
        after = Image.open(BytesIO(final_png)).convert('RGB')
        self._require(before.size == after.size, 'El render firmado cambió de dimensiones.')
        zoom = float(self.signature_preview['zoom'])
        x0, y0, x1, y1 = self.signature_rect
        # The preview date is provisional; the signed stamp uses the actual CMS
        # signing time. Only the small chosen stamp box is exempt from this
        # comparison. All other page pixels must remain exactly identical.
        margin = 2
        box = (max(0, math.floor(x0*zoom)-margin), max(0, math.floor(y0*zoom)-margin),
               min(before.width, math.ceil(x1*zoom)+margin),
               min(before.height, math.ceil(y1*zoom)+margin))
        difference = ImageChops.difference(before, after)
        difference.paste((0, 0, 0), box)
        self._require(difference.getbbox() is None,
                      'El PDF firmado cambió píxeles fuera del área de la firma.')
        self._require(ImageChops.difference(after.crop(box),
                      Image.new('RGB', (box[2]-box[0], box[3]-box[1]), 'white')).getbbox() is not None,
                      'La apariencia de firma no se dibuja al reabrir el PDF.')
        (self.report_path.parent / 'smoke-v161-firma-final.png').write_bytes(final_png)
        self._step('signed_pdf_render_matches_preview_outside_stamp',
                   tolerance_per_channel=0, excluded_pixel_rect=list(box),
                   source_unchanged=_digest(self.source.read_bytes()) == self.source_hash)
